import type { Exercise } from '../types/exercise.js';

export const EXERCISE_CATALOG: Exercise[] = [
  // Cardio
  { id: 'cinta',      name: 'Treadmill',       muscle: 'Cardio' },
  { id: 'eliptica',   name: 'Elliptical',       muscle: 'Cardio' },
  { id: 'bici',       name: 'Stationary Bike',  muscle: 'Cardio' },
  { id: 'escaladora', name: 'Stair Climber',    muscle: 'Cardio' },
  // Chest
  { id: 'bp',                   name: 'Bench Press',              muscle: 'Chest' },
  { id: 'pi',                   name: 'Incline Press',            muscle: 'Chest' },
  { id: 'press_mancuerna',      name: 'Flat Dumbbell Press',      muscle: 'Chest' },
  { id: 'press_mancuerna_incl', name: 'Incline Dumbbell Press',   muscle: 'Chest' },
  { id: 'ap',                   name: 'Dumbbell Flyes',           muscle: 'Chest' },
  { id: 'ap_incl',              name: 'Incline Dumbbell Flyes',   muscle: 'Chest' },
  { id: 'polea_cruce',          name: 'Cable Crossover',          muscle: 'Chest' },
  { id: 'polea_cruce_baja',     name: 'Low Cable Fly',            muscle: 'Chest' },
  { id: 'pullover_m',           name: 'Dumbbell Pullover',        muscle: 'Chest' },
  { id: 'pecho_maq',            name: 'Chest Press Machine',      muscle: 'Chest' },
  { id: 'pec_deck',             name: 'Pec Deck',                 muscle: 'Chest' },
  { id: 'fondos_maq',           name: 'Machine Dips',             muscle: 'Chest' },
  { id: 'hs_chest',             name: 'Hammer Strength Chest',    muscle: 'Chest' },
  { id: 'hs_incline',           name: 'Hammer Strength Incline',  muscle: 'Chest' },
  { id: 'pec_fly',              name: 'Pec Fly Machine',          muscle: 'Chest' },
  { id: 'cable_fly_high',       name: 'High Cable Fly',           muscle: 'Chest' },
  // Back
  { id: 'dom',           name: 'Pull Ups',                  muscle: 'Back' },
  { id: 'dom_asist',     name: 'Assisted Pull-up',          muscle: 'Back' },
  { id: 'jal',           name: 'Lat Pulldown',              muscle: 'Back' },
  { id: 'polea_recta',   name: 'Straight-Arm Pulldown',     muscle: 'Back' },
  { id: 'pull_polea',    name: 'Cable Pullover',            muscle: 'Back' },
  { id: 'face_pull',     name: 'Face Pull',                 muscle: 'Back' },
  { id: 'rem',           name: 'Barbell Row',               muscle: 'Back' },
  { id: 'remo_t',        name: 'T-Bar Row',                 muscle: 'Back' },
  { id: 'remo_m',        name: 'Dumbbell Row',              muscle: 'Back' },
  { id: 'remo_maq',      name: 'Seated Row Machine',        muscle: 'Back' },
  { id: 'hs_row',          name: 'Hammer Strength Row',     muscle: 'Back' },
  { id: 'hs_pulldown',     name: 'Hammer Strength Pulldown',muscle: 'Back' },
  { id: 'chest_supported', name: 'Chest Supported Row',     muscle: 'Back' },
  { id: 'rev_pec_fly',     name: 'Reverse Pec Fly',         muscle: 'Back' },
  // Legs
  { id: 'sen',          name: 'Squat',                      muscle: 'Legs' },
  { id: 'sen_goblet',   name: 'Goblet Squat',               muscle: 'Legs' },
  { id: 'hack',         name: 'Hack Squat',                 muscle: 'Legs' },
  { id: 'pm',           name: 'Deadlift',                   muscle: 'Legs' },
  { id: 'rdl_m',        name: 'Dumbbell RDL',               muscle: 'Legs' },
  { id: 'pren',         name: 'Leg Press',                  muscle: 'Legs' },
  { id: 'hip',          name: 'Hip Thrust',                 muscle: 'Legs' },
  { id: 'pull_through', name: 'Cable Pull-Through',         muscle: 'Legs' },
  { id: 'zancada_m',    name: 'Dumbbell Lunges',            muscle: 'Legs' },
  { id: 'ext',          name: 'Leg Extension',              muscle: 'Legs' },
  { id: 'fem_tumb',     name: 'Lying Leg Curl',             muscle: 'Legs' },
  { id: 'patada_polea', name: 'Cable Kickback',             muscle: 'Legs' },
  { id: 'abduct',       name: 'Abductor Machine',           muscle: 'Legs' },
  { id: 'adduct',       name: 'Adductor Machine',           muscle: 'Legs' },
  { id: 'gem_maq',      name: 'Calf Raise Machine',         muscle: 'Legs' },
  { id: 'gem_m',        name: 'Single-Leg Calf Raise',      muscle: 'Legs' },
  { id: 'hs_leg_press', name: 'Hammer Strength Leg Press',  muscle: 'Legs' },
  { id: 'fem_sent',     name: 'Seated Leg Curl',            muscle: 'Legs' },
  { id: 'bulgarian',    name: 'Bulgarian Split Squat',      muscle: 'Legs' },
  // Shoulders
  { id: 'pmil',          name: 'Military Press',            muscle: 'Shoulders' },
  { id: 'pmil_m',        name: 'Dumbbell Shoulder Press',   muscle: 'Shoulders' },
  { id: 'arnold',        name: 'Arnold Press',              muscle: 'Shoulders' },
  { id: 'elevl',         name: 'Lateral Raises',            muscle: 'Shoulders' },
  { id: 'elevl_polea',   name: 'Cable Lateral Raise',       muscle: 'Shoulders' },
  { id: 'elevf',         name: 'Front Raises',              muscle: 'Shoulders' },
  { id: 'pajaro',        name: 'Rear Delt Fly',             muscle: 'Shoulders' },
  { id: 'polea_rear',    name: 'Cable Rear Delt Fly',       muscle: 'Shoulders' },
  { id: 'remo_verti',    name: 'Upright Row',               muscle: 'Shoulders' },
  { id: 'hs_shoulder',   name: 'Hammer Strength Shoulder',  muscle: 'Shoulders' },
  { id: 'lat_raise_maq', name: 'Lateral Raise Machine',     muscle: 'Shoulders' },
  { id: 'cable_front',   name: 'Cable Front Raise',         muscle: 'Shoulders' },
  // Arms
  { id: 'curlb',             name: 'Barbell Curl',               muscle: 'Arms' },
  { id: 'curlm',             name: 'Hammer Curl',                muscle: 'Arms' },
  { id: 'curl_incl',         name: 'Incline Dumbbell Curl',      muscle: 'Arms' },
  { id: 'curl_polea',        name: 'Cable Curl',                 muscle: 'Arms' },
  { id: 'curl_inv',          name: 'Reverse Curl',               muscle: 'Arms' },
  { id: 'pred_maq',          name: 'Preacher Curl Machine',      muscle: 'Arms' },
  { id: 'curl_conc',         name: 'Concentration Curl',         muscle: 'Arms' },
  { id: 'polea',             name: 'Cable Triceps',              muscle: 'Arms' },
  { id: 'tri_soga',          name: 'Triceps Rope Pushdown',      muscle: 'Arms' },
  { id: 'tri_copa',          name: 'Overhead Extension',         muscle: 'Arms' },
  { id: 'tri_m',             name: 'Dumbbell Triceps Extension', muscle: 'Arms' },
  { id: 'tri_polea_alta',    name: 'Cable Overhead Triceps',     muscle: 'Arms' },
  { id: 'skull_crusher',     name: 'Skull Crusher',              muscle: 'Arms' },
  { id: 'tricep_kickback_m', name: 'Tricep Kickback',            muscle: 'Arms' },
  { id: 'cable_curl_high',   name: 'High Cable Curl',            muscle: 'Arms' },
  { id: 'bayesian_curl',     name: 'Bayesian Curl',              muscle: 'Arms' },
  // Abs
  { id: 'plank',        name: 'Plank',        muscle: 'Abs' },
  { id: 'crunch',       name: 'Crunch',       muscle: 'Abs' },
  { id: 'crunch_polea', name: 'Cable Crunch', muscle: 'Abs' },
  { id: 'woodchop',     name: 'Wood Chop',    muscle: 'Abs' },
  { id: 'twist_ruso',   name: 'Russian Twist',muscle: 'Abs' },
  { id: 'leg_raise',    name: 'Leg Raises',   muscle: 'Abs' },
  { id: 'ab_wheel',     name: 'Ab Wheel',     muscle: 'Abs' },
];

/** Secondary muscle groups per exercise ID (comma-separated English names) */
export const SECONDARY_MUSCLES: Record<string, string> = {
  bp: 'Arms,Shoulders', pi: 'Arms,Shoulders',
  press_mancuerna: 'Arms,Shoulders', press_mancuerna_incl: 'Arms,Shoulders',
  hs_chest: 'Arms,Shoulders', hs_incline: 'Arms,Shoulders',
  pec_fly: 'Arms', cable_fly_high: 'Arms,Shoulders',
  dom: 'Arms', dom_asist: 'Arms', jal: 'Arms', rem: 'Arms',
  remo_t: 'Arms', remo_m: 'Arms', remo_maq: 'Arms',
  hs_row: 'Arms', hs_pulldown: 'Arms',
  sen: 'Back,Abs', hack: 'Back', pm: 'Back,Arms',
  hip: 'Abs', pren: 'Abs', sen_goblet: 'Abs',
  pmil: 'Arms', pmil_m: 'Arms', arnold: 'Arms',
  cinta: 'Legs,Abs', eliptica: 'Legs,Arms', bici: 'Legs',
};
