import type { Exercise } from '../types/exercise.js';

export const EXERCISE_CATALOG: Exercise[] = [
  // Cardio
  { id: 'cinta',      name: 'Treadmill',       muscle: 'Cardio' },
  { id: 'eliptica',   name: 'Elliptical',       muscle: 'Cardio' },
  { id: 'bici',       name: 'Stationary Bike',  muscle: 'Cardio' },
  { id: 'escaladora', name: 'Stair Climber',    muscle: 'Cardio' },
  // Chest
  { id: 'bp',                   name: 'Bench Press',              muscle: 'Chest' },
  { id: 'pi',                   name: 'Incline Press',            muscle: 'Chest' },
  { id: 'press_mancuerna',      name: 'Flat Dumbbell Press',      muscle: 'Chest' },
  { id: 'press_mancuerna_incl', name: 'Incline Dumbbell Press',   muscle: 'Chest' },
  { id: 'ap',                   name: 'Dumbbell Flyes',           muscle: 'Chest' },
  { id: 'ap_incl',              name: 'Incline Dumbbell Flyes',   muscle: 'Chest' },
  { id: 'polea_cruce',          name: 'Cable Crossover',          muscle: 'Chest' },
  { id: 'polea_cruce_baja',     name: 'Low Cable Fly',            muscle: 'Chest' },
  { id: 'pullover_m',           name: 'Dumbbell Pullover',        muscle: 'Chest' },
  { id: 'pecho_maq',            name: 'Chest Press Machine',      muscle: 'Chest' },
  { id: 'pec_deck',             name: 'Pec Deck',                 muscle: 'Chest' },
  { id: 'fondos_maq',           name: 'Machine Dips',             muscle: 'Chest' },
  { id: 'hs_chest',             name: 'Hammer Strength Chest',    muscle: 'Chest' },
  { id: 'hs_incline',           name: 'Hammer Strength Incline',  muscle: 'Chest' },
  { id: 'pec_fly',              name: 'Pec Fly Machine',          muscle: 'Chest' },
  { id: 'cable_fly_high',       name: 'High Cable Fly',           muscle: 'Chest' },
  { id: 'cable_fly_neutral',    name: 'Neutral Cable Fly',        muscle: 'Chest' },
  // Back
  { id: 'dom',           name: 'Pull Ups',                  muscle: 'Back' },
  { id: 'dom_asist',     name: 'Assisted Pull-up',          muscle: 'Back' },
  { id: 'jal',           name: 'Lat Pulldown',              muscle: 'Back' },
  { id: 'polea_recta',   name: 'Straight-Arm Pulldown',     muscle: 'Back' },
  { id: 'pull_polea',    name: 'Cable Pullover',            muscle: 'Back' },
  { id: 'face_pull',     name: 'Face Pull',                 muscle: 'Back' },
  { id: 'rem',           name: 'Barbell Row',               muscle: 'Back' },
  { id: 'remo_t',        name: 'T-Bar Row',                 muscle: 'Back' },
  { id: 'remo_m',        name: 'Dumbbell Row',              muscle: 'Back' },
  { id: 'remo_maq',      name: 'Seated Row Machine',        muscle: 'Back' },
  { id: 'hs_row',          name: 'Hammer Strength Row',     muscle: 'Back' },
  { id: 'hs_pulldown',     name: 'Hammer Strength Pulldown',muscle: 'Back' },
  { id: 'chest_supported', name: 'Chest Supported Row',     muscle: 'Back' },
  { id: 'rev_pec_fly',          name: 'Reverse Pec Fly',        muscle: 'Back' },
  { id: 'single_arm_cable_row', name: 'Single-Arm Cable Row',   muscle: 'Back' },
  // Legs
  { id: 'sen',          name: 'Squat',                      muscle: 'Legs' },
  { id: 'sen_goblet',   name: 'Goblet Squat',               muscle: 'Legs' },
  { id: 'hack',         name: 'Hack Squat',                 muscle: 'Legs' },
  { id: 'pm',           name: 'Deadlift',                   muscle: 'Legs' },
  { id: 'rdl_m',        name: 'Dumbbell RDL',               muscle: 'Legs' },
  { id: 'pren',         name: 'Leg Press',                  muscle: 'Legs' },
  { id: 'hip',          name: 'Hip Thrust',                 muscle: 'Legs' },
  { id: 'pull_through', name: 'Cable Pull-Through',         muscle: 'Legs' },
  { id: 'zancada_m',    name: 'Dumbbell Lunges',            muscle: 'Legs' },
  { id: 'ext',          name: 'Leg Extension',              muscle: 'Legs' },
  { id: 'fem_tumb',     name: 'Lying Leg Curl',             muscle: 'Legs' },
  { id: 'patada_polea',       name: 'Cable Kickback',            muscle: 'Legs' },
  { id: 'glute_kickback_maq',name: 'Glute Kickback Machine',    muscle: 'Legs' },
  { id: 'donkey_kick',        name: 'Donkey Kick',               muscle: 'Legs' },
  { id: 'hip_dip',            name: 'Hip Dip',                   muscle: 'Legs' },
  { id: 'glute_bridge',       name: 'Glute Bridge',              muscle: 'Legs' },
  { id: 'sumo_squat',         name: 'Sumo Squat',                muscle: 'Legs' },
  { id: 'step_up',            name: 'Step Up',                   muscle: 'Legs' },
  { id: 'cable_hip_abduct',   name: 'Cable Hip Abduction',       muscle: 'Legs' },
  { id: 'cable_hip_adduct',   name: 'Cable Hip Adduction',       muscle: 'Legs' },
  { id: 'abduct',             name: 'Abductor Machine',          muscle: 'Legs' },
  { id: 'adduct',             name: 'Adductor Machine',          muscle: 'Legs' },
  { id: 'gem_maq',            name: 'Calf Raise Machine',        muscle: 'Legs' },
  { id: 'gem_m',              name: 'Single-Leg Calf Raise',     muscle: 'Legs' },
  { id: 'hs_leg_press',       name: 'Hammer Strength Leg Press', muscle: 'Legs' },
  { id: 'fem_sent',           name: 'Seated Leg Curl',           muscle: 'Legs' },
  { id: 'bulgarian',          name: 'Bulgarian Split Squat',     muscle: 'Legs' },
  // Shoulders
  { id: 'pmil',          name: 'Military Press',            muscle: 'Shoulders' },
  { id: 'pmil_m',        name: 'Dumbbell Shoulder Press',   muscle: 'Shoulders' },
  { id: 'arnold',        name: 'Arnold Press',              muscle: 'Shoulders' },
  { id: 'elevl',         name: 'Lateral Raises',            muscle: 'Shoulders' },
  { id: 'elevl_polea',   name: 'Cable Lateral Raise',       muscle: 'Shoulders' },
  { id: 'elevf',         name: 'Front Raises',              muscle: 'Shoulders' },
  { id: 'pajaro',        name: 'Rear Delt Fly',             muscle: 'Shoulders' },
  { id: 'polea_rear',    name: 'Cable Rear Delt Fly',       muscle: 'Shoulders' },
  { id: 'remo_verti',    name: 'Upright Row',               muscle: 'Shoulders' },
  { id: 'hs_shoulder',   name: 'Hammer Strength Shoulder',  muscle: 'Shoulders' },
  { id: 'lat_raise_maq', name: 'Lateral Raise Machine',     muscle: 'Shoulders' },
  { id: 'cable_front',   name: 'Cable Front Raise',         muscle: 'Shoulders' },
  { id: 'cable_y_raise', name: 'Cable Y Raise',             muscle: 'Shoulders' },
  // Arms
  { id: 'curlb',             name: 'Barbell Curl',               muscle: 'Arms' },
  { id: 'curlm',             name: 'Hammer Curl',                muscle: 'Arms' },
  { id: 'curl_incl',         name: 'Incline Dumbbell Curl',      muscle: 'Arms' },
  { id: 'curl_polea',        name: 'Cable Curl',                 muscle: 'Arms' },
  { id: 'curl_inv',          name: 'Reverse Curl',               muscle: 'Arms' },
  { id: 'pred_maq',          name: 'Preacher Curl Machine',      muscle: 'Arms' },
  { id: 'curl_conc',         name: 'Concentration Curl',         muscle: 'Arms' },
  { id: 'polea',             name: 'Cable Triceps',              muscle: 'Arms' },
  { id: 'tri_soga',          name: 'Triceps Rope Pushdown',      muscle: 'Arms' },
  { id: 'tri_copa',          name: 'Overhead Extension',         muscle: 'Arms' },
  { id: 'tri_m',             name: 'Dumbbell Triceps Extension', muscle: 'Arms' },
  { id: 'tri_polea_alta',    name: 'Cable Overhead Triceps',     muscle: 'Arms' },
  { id: 'skull_crusher',          name: 'Skull Crusher',              muscle: 'Arms' },
  { id: 'tricep_kickback_m',      name: 'Tricep Kickback',            muscle: 'Arms' },
  { id: 'tricep_kickback_cable',  name: 'Cable Tricep Kickback',      muscle: 'Arms' },
  { id: 'incline_kickback',       name: 'Incline Tricep Kickback',    muscle: 'Arms' },
  { id: 'cable_curl_high',        name: 'High Cable Curl',            muscle: 'Arms' },
  { id: 'bayesian_curl',          name: 'Bayesian Curl',              muscle: 'Arms' },
  // Abs
  { id: 'plank',              name: 'Plank',                muscle: 'Abs' },
  { id: 'side_plank',         name: 'Side Plank',           muscle: 'Abs' },
  { id: 'crunch',             name: 'Crunch',               muscle: 'Abs' },
  { id: 'bicycle_crunch',     name: 'Bicycle Crunch',       muscle: 'Abs' },
  { id: 'reverse_crunch',     name: 'Reverse Crunch',       muscle: 'Abs' },
  { id: 'crunch_polea',       name: 'Cable Crunch',         muscle: 'Abs' },
  { id: 'woodchop',           name: 'Wood Chop',            muscle: 'Abs' },
  { id: 'twist_ruso',         name: 'Russian Twist',        muscle: 'Abs' },
  { id: 'leg_raise',          name: 'Leg Raises',           muscle: 'Abs' },
  { id: 'hanging_leg_raise',  name: 'Hanging Leg Raise',    muscle: 'Abs' },
  { id: 'toes_to_bar',        name: 'Toes to Bar',          muscle: 'Abs' },
  { id: 'v_up',               name: 'V-Up',                 muscle: 'Abs' },
  { id: 'dead_bug',           name: 'Dead Bug',             muscle: 'Abs' },
  { id: 'hollow_hold',        name: 'Hollow Hold',          muscle: 'Abs' },
  { id: 'mountain_climber',   name: 'Mountain Climber',     muscle: 'Abs' },
  { id: 'dragon_flag',        name: 'Dragon Flag',          muscle: 'Abs' },
  { id: 'ab_wheel',           name: 'Ab Wheel',             muscle: 'Abs' },
  { id: 'pallof_press',       name: 'Pallof Press',         muscle: 'Abs' },
  { id: 'cable_oblique',      name: 'Cable Oblique Crunch', muscle: 'Abs' },
  { id: 'flutter_kick',       name: 'Flutter Kicks',        muscle: 'Abs' },
  { id: 'scissor_kick',       name: 'Scissor Kicks',        muscle: 'Abs' },
  { id: 'toe_touch',          name: 'Toe Touch Crunch',     muscle: 'Abs' },
  { id: 'seated_leg_raise',   name: 'Seated Leg Raise',     muscle: 'Abs' },
  { id: 'superman',           name: 'Superman',             muscle: 'Abs' },
  { id: 'bird_dog',           name: 'Bird Dog',             muscle: 'Abs' },
  // Inverse superman & hollow body progressions
  { id: 'reverse_superman',   name: 'Reverse Superman',     muscle: 'Abs' },
  { id: 'hollow_rock',        name: 'Hollow Body Rock',     muscle: 'Abs' },
  { id: 'tuck_hollow',        name: 'Tuck Hollow Hold',     muscle: 'Abs' },
  { id: 'windshield_wiper',   name: 'Windshield Wipers',    muscle: 'Abs' },
  { id: 'l_sit',              name: 'L-Sit',                muscle: 'Abs' },
  { id: 'boat_pose',          name: 'Boat Pose',            muscle: 'Abs' },
  // Flexibility
  { id: 'hip_flexor_stretch', name: 'Hip Flexor Stretch',   muscle: 'Flexibility' },
  { id: 'hamstring_stretch',  name: 'Hamstring Stretch',    muscle: 'Flexibility' },
  { id: 'quad_stretch',       name: 'Quad Stretch',         muscle: 'Flexibility' },
  { id: 'pigeon_pose',        name: 'Pigeon Pose',          muscle: 'Flexibility' },
  { id: 'butterfly_stretch',  name: 'Butterfly Stretch',    muscle: 'Flexibility' },
  { id: 'child_pose',         name: "Child's Pose",         muscle: 'Flexibility' },
  { id: 'downward_dog',       name: 'Downward Dog',         muscle: 'Flexibility' },
  { id: 'cat_cow',            name: 'Cat-Cow',              muscle: 'Flexibility' },
  { id: 'spine_twist',        name: 'Seated Spine Twist',   muscle: 'Flexibility' },
  { id: 'chest_stretch',      name: 'Chest Stretch',        muscle: 'Flexibility' },
  { id: 'shoulder_stretch',   name: 'Cross-Body Shoulder Stretch', muscle: 'Flexibility' },
  { id: 'foam_roll_back',     name: 'Foam Roll Back',       muscle: 'Flexibility' },
  { id: 'foam_roll_legs',     name: 'Foam Roll Legs',       muscle: 'Flexibility' },
  { id: 'world_greatest',     name: 'World Greatest Stretch', muscle: 'Flexibility' },
  { id: 'couch_stretch',      name: 'Couch Stretch',        muscle: 'Flexibility' },
];

/** Secondary muscle groups per exercise ID (comma-separated English names) */
export const SECONDARY_MUSCLES: Record<string, string> = {
  bp: 'Arms,Shoulders', pi: 'Arms,Shoulders',
  press_mancuerna: 'Arms,Shoulders', press_mancuerna_incl: 'Arms,Shoulders',
  hs_chest: 'Arms,Shoulders', hs_incline: 'Arms,Shoulders',
  pec_fly: 'Arms', cable_fly_high: 'Arms,Shoulders',
  dom: 'Arms', dom_asist: 'Arms', jal: 'Arms', rem: 'Arms',
  remo_t: 'Arms', remo_m: 'Arms', remo_maq: 'Arms',
  hs_row: 'Arms', hs_pulldown: 'Arms',
  sen: 'Back,Abs', hack: 'Back', pm: 'Back,Arms',
  hip: 'Abs', pren: 'Abs', sen_goblet: 'Abs',
  pmil: 'Arms', pmil_m: 'Arms', arnold: 'Arms',
  cinta: 'Legs,Abs', eliptica: 'Legs,Arms', bici: 'Legs',
};
